meta_name: "Nomadmap"
meta_title: "Nomadmap | Digital Nomads Finder"
meta_description: "Where digital nomads share their real-time location with their peers"
meta_image: "https://raw.githubusercontent.com/CharlyMartin/nomadmap-icons/master/logos/big_squared.png"
facebook_app_id: "102688966994695"
